version: "3.8"

services:
  android:
    container_name: android
    build:
      context: .
      dockerfile: ./docker/android
    image: hikup/android
    command: [ "${ANDROID_CMD}" ]
    volumes:
      - ./app/lib:/usr/app/lib:rw
      - ./app/config:/usr/app/config:ro
      - ./app/assets:/usr/app/assets:ro
      - ./app/test:/usr/app/test:ro

      - ./app/apk:/usr/app/apk:rw
      - ./app/coverage:/usr/app/coverage:rw

      - ./app/pubspec.yaml:/usr/app/pubspec.yaml:rw
      - ./app/pubspec.lock:/usr/app/pubspec.lock:rw
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      network:
        ipv4_address: 172.20.0.2
    stdin_open: true
#   tty: true

networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
          gateway: "172.20.0.1"
