version: "3"
services:
  build:
    container_name: hikup_android_apk
    build:
      context: ./
      dockerfile: build.dok
    image: hikup/android/apk
    volumes:
      - ./apk/:/usr/src/app/build/app/outputs/flutter-apk/
    stdin_open: true

  test:
    container_name: hikup_android_tst
    build:
      context: ./
      dockerfile: test.dok
    image: hikup/android/test
    volumes:
      - ./:/usr/src/app/
    stdin_open: true

  dev:
    container_name: hikup_android_dev
    build:
      context: ./
      dockerfile: dev.dok
    image: hikup/android/dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app/
    stdin_open: true
    tty: true
