name: hikup
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  google_fonts: ^6.1.0
  intl: ^0.18.0
  url_launcher: ^6.1.10
  shared_preferences: ^2.0.12
  geolocator: ^10.1.0
  auto_size_text: ^3.0.0
  pinput: ^3.0.1
  fluttertoast: ^8.0.9
  provider:
  get_it:
  dio:
  font_awesome_flutter:
  gap:
  flutter_dotenv:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.6.1
  flutter_local_notifications: ^16.1.0
  firebase_core_platform_interface: ^5.0.0
  firebase_messaging: ^14.2.4
  image_picker: ^1.0.4
  firebase_storage:
  cached_network_image: ^3.2.3
  flutter_map_location_marker: ^8.0.0
  rename: ^3.0.0
  carousel_slider: ^4.2.1
  permission_handler: ^11.0.0
  flutter_svg: ^2.0.9
  sliding_up_panel: ^2.0.0+1
  any_link_preview: ^3.0.0
  socket_io_client: ^2.0.2
  latlong2: ^0.9.0
  visibility_detector: ^0.4.0+2
  flutter_stripe: ^3.2.0
  firebase_analytics: ^10.5.1
  firebase_crashlytics: ^3.3.7
  flutter_map: ^6.0.1
  flutter_map_cache: ^1.3.1
  path_provider: ^2.1.1
  dio_cache_interceptor_hive_store: ^3.2.1
  uuid: ^4.1.0
  flutter_rating_bar: ^4.0.1
  dio_cache_interceptor: ^3.4.4
  collection: ^1.17.2
  flutter_compass: ^0.8.0
  onboarding: ^3.1.0
  pedometer: ^4.0.1
  perfect_volume_control:
  audioplayers:
  timezone: ^0.9.2
  mixpanel_flutter: ^2.2.0
  flutter_localization: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/achievements/
    - assets/icons/start/
    - assets/icons/details/
    - assets/sounds/
    - assets/trails/ancien_cimetiere_parisien/
    - assets/trails/balade-parisienne/
    - assets/trails/castanet-le-chemin-des-moines/
    - assets/trails/chapelleneuve-3chapelles-16-5km/
    - assets/trails/etangs_de_meudon_villebon_la_garenne_chalais_et_trivaux/
    - assets/trails/faculte-de-tolbiac/
    - assets/trails/foret_de_sapins/
    - assets/trails/fougeres-villeetforet-18km/
    - assets/trails/gr75/
    - assets/trails/grand-turrel-maraval/
    - assets/trails/l-etoile-long/
    - assets/trails/la-bretagne-parisienne/
    - assets/trails/la_montagne_du_rey_depuis_louvie_juzon/
    - assets/trails/le-bois-de-vincennes/
    - assets/trails/les-carrieres-de-cochin/
    - assets/trails/les-coteaux-de-glanes/
    - assets/trails/limours/
    - assets/trails/marais-du-pont-de-gau/
    - assets/trails/mery-duranderie-courte/
    - assets/trails/mini-tour-du-morvan-e2-saint-brisson-moux-en-morvan/
    - assets/trails/moncaut-8-5-km/
    - assets/trails/morning-hike/
    - assets/trails/nalliers-leshuttes-21-4km/
    - assets/trails/parc-de-choisy-lac-creteil/
    - assets/trails/parcours-des-amis-d-harpignies/
    - assets/trails/parcours-resistantes-c215/
    - assets/trails/paris-balade-du-11e-au-3e/
    - assets/trails/paris-charonne-tour-du-bois-de-vincennes/
    - assets/trails/porte-de-brancion-au-pont-de-sevres/
    - assets/trails/porte-de-versailles-a-henri-martin/
    - assets/trails/porte-doree-a-neuilly-plaisance/
    - assets/trails/praperier-07/
    - assets/trails/pyrenees-boucle-depuis-bidarray-d-harriandi/
    - assets/trails/quartier-chinois-paris/
    - assets/trails/rando-boisbreteau-9-8-km/
    - assets/trails/rando-sep-40km-2024/
    - assets/trails/saint-ilpize-lavoute/
    - assets/trails/standrebohon-marais-10km/
    - assets/trails/stloupthouet-cebronetthouet-19km/
    - assets/trails/street-art-dans-le-13eme-arrondissement/
    - assets/trails/sur-les-pas-de-georges-brassens/
    - assets/trails/tete-de-pibossan-1620-m/
    - assets/trails/tour-parmentier/
    - assets/trails/tour_du_bas_folin_et_du_haut_folin/
    - assets/trails/un-tour-au-cimetiere-du-pere-lachaise/
    - assets/trails/variante-mad-et-madine/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
