name: build_apk

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compose
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'

      - name: Build
        shell: bash
        run: docker-compose up build
