on:
  push:
    branches:
      - master

name: ci

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install app
        shell: bash
        run: ./app.sh docker install

      - name: requirements
        shell: bash
        run: |
          touch ./app/config/.env

      - name: test app
        shell: bash
        run: ./app.sh docker test
